version: '3.3'

services:
  account-svc:
    container_name: dueit_svc_auth
    build: .
    ports:
      - '7002:9090'
    volumes:
      - type: bind
        source: ./.env
        target: /app_repository/.env
        read_only: true
    networks:
      - dueit_network

networks:
  dueit_network:
    external: true