name: service auth ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: login to docker github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: build and push
        run: |
          docker build -f deploy/Dockerfile . --tag ghcr.io/dueit-jasanya-aturuang/doraemon-service:1.0
          docker push ghcr.io/dueit-jasanya-aturuang/doraemon-service:1.0